# YOUR NAME OR TITLE OF YOUR SITE
name: Family Fun Trivia
title: Family Fun Trivia Links

url: "https://links.famfuntrivia.com"
repository: JackAce/links.famfuntrivia.com

# YOUR BRAND/PERSONAL TAGLINE
tagline: Kid-Friendly Trivia Content

# YOUR/BRAND IMAGE URL
Image_URL: https://links.famfuntrivia.com/assets/images/fft-logo-v2-1024x1024.png

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://picsum.photos/1080?nocache=
# Cover_Image: /assets/images/jackace-background-5120x1440.png

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
  # JackAce web site
  - Name: Family Fun Trivia Web Site
    URL: https://www.famfuntrivia.com
    Icon-Class: fas fa-link
    Color: '#3383c0'
    Text_Color: '#fff'

    # YOUTUBE
  - Name: Family Fun Trivia YouTube
    URL: https://www.youtube.com
    Username: /@FamFunTrivia
    Color: '#f00'
    Icon-Class: fab fa-youtube

     # PATREON
  - Name: Patreon
    URL: https://www.patreon.com
    Username: FamilyFunTrivia
    Color: '#FE2C55'
    Icon-Class: fab fa-patreon

    # EMAIL
  - Name: Email
    URL: 'mailto:suggestions@famfuntrivia.com'
    Icon-Class: fas fa-envelope
    Color: '#e17055'
    Text_Color: '#fff'

    # SHOP
  - Name: The JackAce Store
    URL: https://shop.jackace.com
    Color: '#055fa8'
    Icon-Class: fas fa-shopping-cart

  - Name: Links
    URL: https://github.com/JackAce/links.famfuntrivia.com
    Icon-Class: fas fa-link
    Color: '#d94869'
    Text_Color: '#fff'

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: 'No'

google_analytics: G-JH0NSKP8H8

port: 4099

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

# fixes "No GitHub API authentication" error
github: [metadata]
